// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("fs.UnionCase")>]
[<assembly: AssemblyProductAttribute("fs.UnionCase")>]
[<assembly: AssemblyDescriptionAttribute("helper functions for DiscriminateUnions")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "fs.UnionCase"
    let [<Literal>] AssemblyProduct = "fs.UnionCase"
    let [<Literal>] AssemblyDescription = "helper functions for DiscriminateUnions"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
